# Site settings
title: Albert Pető
email: petoalbert32@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: petoalbert
description: "I am Albert, a Hungarian computer science student. This is
the place where I publish posts about my experiences as a programmer."
url: "http://petoalbert.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
